sudo: required
group: edge

services:
  - docker

language: bash

env:
  - REPO=caperneoignis/chrome-headless-browser APACHE_WEB_ROOT=$PWD

before_install:
  # run the previous version if needed.
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - docker build -t $REPO .
before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
script:
  - docker run -d -e APACHE_WEB_ROOT --name chrome1 $REPO
  #we want the version information, so run the image then do an exec command
  - VERSION1=`docker exec chrome1 google-chrome-stable --version | grep -Po '(?<=Google Chrome )[^ ]+'`
  - docker tag $REPO $REPO:${VERSION1}_apache
  - docker tag $REPO $REPO:latest_apache
  - docker run --name chrome -e APACHE_WEB_ROOT  -d --cap-add=SYS_ADMIN $REPO:${VERSION1}_apache --dump-dom http://info.cern.ch/hypertext/WWW/TheProject.html

after_success:
  - docker push $REPO;
    
after_script:
  - docker stop chrome chrome1 && docker rm chrome chrome1
  - docker logout
